services:
  devopsdb:
    image: yaswanth21321/private_test:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: yaswanth21321/private_test:appimage
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
